### ISSUE TITLE
Install the latest version of Heroku CLI toolbelt

### ISSUE THREAD

**Issue by Yanchek99** [wercker/step-heroku-deploy#33]
I have the following property `install-toolbelt: true` configured.  However my run commands no longer work with the following error:

```
WARNING: This is the legacy Heroku CLI with limited functionality. Please install the latest CLI.
WARNING: Installation instructions are at https://cli.heroku.com
module.js:472
    throw err;
    ^

Error: Cannot find module 'heroku-run'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.cache/heroku/tmp/heroku-script-117209765:10:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by maxshelley** [comment]
@Yanchek99 I'm experiencing the same issue, did you get this resolved at all?

**Comment by Yanchek99** [comment]
@maxshelly Yes see my pull request #34
